version: "2.1"
services:
  config:
    image: usefulmana/config-service
    restart: always
    ports:
      - "8888:8888"

  registry:
    image: usefulmana/service-registry
    restart: always
    depends_on:
      - config
    ports:
      - "8761:8761"

  gateway:
    image: usefulmana/api-gateway
    restart: always
    depends_on:
      - config
    ports:
      - "8080:8080"


