version: "2.1"
services:
  config:
    build: ./config-service
    restart: always
    ports:
      - "8888:8888"

  registry:
    build: ./service-registry
    restart: always
    depends_on:
      - config
    ports:
      - "8761:8761"

  gateway:
    build: ./api-gateway
    restart: always
    depends_on:
      - config
    ports:
      - "8080:8080"


