version: 2.1

jobs:
  auth-backend-test:
    working_directory: ~/auth
    docker:
      - image:  circleci/node:10
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: npm install
      - run: 
          name: Run test
          command: npm test
   
    
      
workflows:
  automated-testing:
    jobs:
      - auth-backend-test:
        filters:
          branches:
            ignore:
              - master