version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  frontend-test:
    working_directory: ~/frontend
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run: npm test
  frontend-build:
    working_directory: ~/frontend
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  backend-build-test:
    working_directory: ~/backend
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run: npm test

workflows:
  automated-testing:
    jobs:
      - backend-build-test:
        filters:
          branches:
            ignore:
              - master
      - frontend-test:
        filters:
          branches:
            ignore:
              - master
      - frontend-build:
        filters:
          branches:
            ignore:
              - master
