version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  node: circleci/node@4.0.0

jobs:
  backend-build-test:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - run: mvn clean install
  frontend-build-test:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test

workflows:
  automated-testing:
    jobs:
      - backend-build-test
      - frontend-build-test
