version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  node: circleci/node@4.0.0
  heroku: circleci/heroku@1.2.2
  aws-ecs: circleci/aws-ecs@1.3.0

jobs:
  backend-build-test:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - run: cd backend
      - mvn clean install
  frontend-build-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend
      - node/with-cache:
        steps:
          - run: npm install
      - run: npm run test

workflows:
  automated-testing:
    jobs:
      - backend-build
      - frontend-build-test
