version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  
jobs:
  setup-backend-testing:
    steps:
      - run: cd BackEnd

workflows:
  automated-testing:
    jobs:
      - setup-backend-testing
      - maven/test
