eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://pi:GAtech321@sept.pjbjd.mongodb.net/sept?retryWrites=true&w=majority
      database: sept